# Generated by Django 4.1 on 2024-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ffe", "0002_remove_recipe_image_url_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default="recipes/default-image.jpg", upload_to="recipes/"
            ),
        ),
    ]
