# Generated by Django 4.1 on 2024-05-24 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ffe", "0003_alter_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="average_rating",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aperitivo", "Aperitivo"),
                    ("Piatto Principale", "Piatto Principale"),
                    ("Dessert", "Dessert"),
                    ("Drink", "Drink"),
                    ("Snack", "Snack"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cooking_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Facile", "Facile"),
                    ("Media", "Media"),
                    ("Difficile", "Difficile"),
                    ("Esperto", "Esperto"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="recipe",
            name="preparation_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
