# Generated by Django 4.1 on 2024-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ffe", "0010_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aperitivo", "Aperitivo"),
                    ("Piatto Principale", "Piatto Principale"),
                    ("Secondo Piatto", "Secondo Piatto"),
                    ("Contorno", "Contorno"),
                    ("Dessert", "Dessert"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Facile", "Facile"),
                    ("Media", "Media"),
                    ("Difficile", "Difficile"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
